project:
  type: website

website:
  title: "OrthoK Lenses Effect"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Introduction.qmd
        text: Introduction
      - href: Methodology.qmd
        text: Methodology
      - href: Model.qmd
        text: Model
      - href: References.qmd
        text: References       
      - href: Special.qmd
        text: Special note
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



