---
title: "Introduction"
author: "Melissa Ban"
editor: visual
---

In recent years, myopia has become a more and more common problem among children.
Studies have shown that the increased screen time and the reduced outdoor time can increase the
chance of children getting myopia. Especially under the current COVID-19 pandemic,
approximately 80% of the global student populations are affected by various lockdown measures,
leading to significantly increased use of digital devices, which will result in long-term eye
problems, being myopia (Wong et al., 2020). It is also predicted that, by 2050, around 5 billion
people will have myopia (Dolgin, 2015).

						

Myopia is more commonly known as nearsightedness, which occurs when the cornea is
too curved that causes the refraction of light. The image is then formed in front of the retina,
instead of on the retina itself. Patients with myopia can often see nearby objects clearly but
experience blurred farsighted vision (Yu et al., 2011). Moreover, myopia is most commonly
treated using corrective concave lenses, the power (diopter, D) of lenses is prescribed based on
the eye\'s spherical (SPH) power (diopter, D) and cylinder (CYL) power (D), which can be
measured using manifest refraction test (see figure 1 in the appendix). SPH is the power of a
lens, while CYL is the power of astigmatism, which is the imperfection in the curvature of the
eye that blurs out the vision (Mayo Clinic, 2019). SPH and CYL are considered direct
measurements of one\'s vision (Heiting, 2020). Another value, spherical equivalent (SE), as
measured in diopters (D), is a comprehensive measurement of SPH and CYL, that is used to
prescribe contact lenses to an individual with low astigmatism. Because SE is calculated based
on SPH and CYL, the spherical equivalent is also considered a way to evaluate an individual\'s
vision (EyeQue Support, 2021). SPH, CYL, and SE values are often present as negative values
which represent myopia. The higher their absolute value is, the worse the patients\' vision is.

						
The trend of the growing myopia population raises concerns about effective myopia
treatment. Now, the traditional way (glasses) is found less satisfactory to the individuals that
have myopia as it is not as beautiful, and although it can treat the condition, it does not improve
the condition (Wilson & Keeney, 1990). Thus, modern ways of myopia treatments are developed,
with laser surgery and orthokeratology lenses leading the industry. Because laser surgery is
recommended to be taken after 18 years old, orthokeratology lenses then became the choice of
more and more juvenile myopia patients (Kramer, 2018).

						

Orthokeratology lenses, also referred to as OK lenses, can limit the development of
myopia and allow patients to have clear vision during day time without the use of glasses or
contact lenses. There are huge differences between traditional contact lenses and OK lenses, as
the former is soft, not gas-permeable, and is worn throughout the day; while the latter is hard and
gas permeable, and only needs to be worn at night while sleeping. More importantly, traditional
lenses can not control the growth of myopia power, whereas OK lenses are suggested to be
effective (Lipson, 2018). The principle of the use of the hard lens is to put pressure on the
patient\'s cornea at night, remodelling the anterior part of the cornea into a shape where light is
correctly refractured and the image can form exactly on the retina. This change in shape is
temporary, as the human lens tends to reform its original shape over time. Thus, the patient will
experience a change in vision between morning and evening, when their vision starts to blur out.
Later at night, the OK lenses are worn again, flattening the anterior portion of the cornea,
restoring the vision (Yoon & Swarbrick, 2013).

						

However, giving so many advantages of OK lenses, there are still concerns regarding
overnight wearing risks, especially when it is more commonly used among young children (Cho
et al., 2007). Parents are concerned about the right age for their kids to start wearing OK lenses.
As children\'s cornea is more vulnerable than that of adults, questions regarding the treatment\'s
harm to children\'s cornea have been raised (Ostrov, 2015).

	
There are a relatively high number of studies exploring the use and safety hazards of OK
lenses, but not a lot of studies focused on the factor of initial wearing age, which can also be a
potential influencing factor of the treatment result. One study, by Dr. Jayakumar and Swarbrick
(2004), touched on the effect of age on short-term orthokeratology. The study focused on
comparing the effect of children, young adults, and older adults. The conclusion is that all groups
reflect significant improvement in vision, while the group of older adults has less change in
visual acuity, in comparison to children and young adults. Thus, it suggests that age does affect
the result of using OK lenses. The hypothesis in this study has also been made based on the
result from this previous one.

						
In this investigation, the effect of OK lenses on children of different ages is studied using a set of data by Yin et al. (2019).

