---
title: "References"
author: "Melissa Ban"
editor: visual
---

\*PhD†PhD. Posterior Corneal Shape Changes in Myopic Overnight\... : Optometry and Vision
Science. LWW. https://journals.lww.com/optvissci/Fulltext/2013/03000/Posterior_Corneal_Shape_Changes_in_Myopic.3.aspx.\

7 things you didn't know about ortho-K. Healio. https://www.healio.com/news/optometry/20180918/7-things-you-didnt-know-about-orthok.\

Chen, R., Yu, J., Lipson, M., Cheema, A. A., Chen, Y., Lian, H., \... McAlinden, C. (2019,December 4). Comparison of four different orthokeratology lenses in controlling myopia
progression. Contact Lens and Anterior Eye.
https://www.sciencedirect.com/science/article/abs/pii/S1367048419302164.

					

Cho, P., Cheung, S. W., Mountford, J., & White, P. (2008). Good clinical practice in
orthokeratology. Contact Lens and Anterior Eye, 31(1), 17--28.
https://doi.org/10.1016/j.clae.2007.07.003

					

Department of Ophthalmology and Visual Science (M.J.L.). The Role of Orthokeratology in
Myopia Control: A Review : Eye & Contact Lens. LWW.
https://journals.lww.com/claojournal/Abstract/2018/07000/The_Role_of_Orthokeratolog
y_in_Myopia_Control\_\_A.5.aspx.

					

Edited by Joseph P. Shovlin, O. D. (2013, March 15). How to Burst Your Bubble. Review of
Optometry. https://www.reviewofoptometry.com/article/how-to-burst-your-bubble.

					

Frost, J. (2017, May 5). Outliers. Statistics By Jim. https://statisticsbyjim.com/glossary/outliers/.

				

Hease, M., Humphries, M., Sangwin, C. J., & Vo, N. (2019). Mathematics: analysis and
approaches Sl. Hease Mathematics.

					

JAYAKUMAR, J. A. I. K. I. S. H. A. N., & SWARBRICK, H. E. L. E. N. A. (2005). The Effect
of Age on Short-Term Orthokeratology. Optometry and Vision Science, 82(6), 505--511.
https://doi.org/10.1097/01.opx.0000168583.17327.6d

					

A JSTOR Time Line. (2012). JSTOR. https://doi.org/10.1515/9781400843114.xxvii\

Kabosova, A., Azar, D. T., Bannikov, G. A., Campbell, K. P., Durbeej, M., Ghohestani, R. F., \...

					

Ljubimov, A. V. (2007, November). Compositional differences between infant and adult
human corneal basement membranes. Investigative ophthalmology & visual science.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2151758/.

					

Liu, Y. M., & Xie, P. (2016, January). The Safety of Orthokeratology\--A Systematic Review. Eye
& contact lens. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4697954/.

					

Martel, J. (2018, July 3). Refraction Test: Overview, Purpose & Procedure. Healthline.
https://www.healthline.com/health/refraction-test.

					

Mayo Foundation for Medical Education and Research. (2019, September 4). Astigmatism. Mayo
Clinic. https://www.mayoclinic.org/diseases-conditions/astigmatism/symptoms-
causes/syc-20353835.

					

Measurements and Error Analysis.
https://www.webassign.net/question_assets/unccolphysmechl1/measurements/manual.ht
ml.

					

Nature Publishing Group. The myopia boom. Nature News. https://www.nature.com/news/the-
myopia-boom-1.17120.

				

			

		

		

			

				

					

Ortho-K and Kids: Maximize the Benefits. (2012, May 15). Ortho-K and Kids: Maximize the
Benefits, Minimize the Risk. Review of Cornea and Contact Lenses.
https://www.reviewofcontactlenses.com/article/ortho-k-and-kids-maximize-the-benefits-
minimize-the-risk.

					

Percentage Change. Math is Fun. https://www.mathsisfun.com/numbers/percentage-
change.html.

					

A RETROSPECTIVE LOOK AT CHILDREN FIT WITH ORTHO-K---REVISITED.
clspectrum.com. https://www.clspectrum.com/issues/2019/march-2019/a-retrospective-
look-at-children-fit-with-ortho-k.

					

Ruchama. Contact Lenses for the "Hard-to-Fit" Patient. Dolman Eyecare Centre.
https://www.dolmaneyecare.com/eyeglasses-contacts/contact-lenses/contact-lenses-for-
the-hard-to-fit-patient/.

					

Siegle, D. (2015, February 24). r Critical Value Table. Educational Research Basics by Del
Siegle. https://researchbasics.education.uconn.edu/r_critical_value_table/#.

					

Swarbrick, H. A., Alharbi, A., Watt, K., Lum, E., & Kang, P. (2015). Myopia Control during
Orthokeratology Lens Wear in Children Using a Novel Study Design. Ophthalmology,
122(3), 620--630. https://doi.org/10.1016/j.ophtha.2014.09.028

					

Taylor, C. How to Calculate the Correlation Coefficient. ThoughtCo.
https://www.thoughtco.com/how-to-calculate-the-correlation-coefficient-3126228.

					

Team, A. A. V. E. (2021, January 20). Orthokeratology: Correct Your Vision While You Sleep!
All About Vision. https://www.allaboutvision.com/contacts/orthok.htm.

					

Thomas, L. (2021, March 8). Control Groups and Treatment Groups: Uses & Examples. Scribbr.
https://www.scribbr.com/methodology/control-group/.

				

			

		

		

			

				

					

Troy Bedinghaus, O. D. Get Info on How Eye Doctors Test Your Vision With Refraction.
Verywell Health. https://www.verywellhealth.com/refraction-in-your-eye-or-vision-
exam-3421821.

					

Wilson, D. R., & Keeney, A. H. Corrective measures for myopia.
https://www.surveyophthalmol.com/article/0039-6257(90)90028-
T/pdf#secd15880550e46.

					

Wong, C. W., Tsai, A., Jonas, J. B., Ohno-Matsui, K., Chen, J., Ang, M., & Ting, D. S. (2021).
Digital Screen Time During the COVID-19 Pandemic: Risk for a Further Myopia Boom?
American Journal of Ophthalmology, 223, 333--337.
https://doi.org/10.1016/j.ajo.2020.07.034

					

Yin, Y., Zhao, Y., Wu, X., Jiang, M., Xia, X., Chen, Y., \... Wen, D. (2019). One-year effect of
wearing Orthokeratology lenses on the visual quality of juvenile myopia: A retrospective
study. PeerJ, 7. https://doi.org/10.7717/peerj.6998

					

Yoon, J. H., & Swarbrick, H. A. (2013). Posterior Corneal Shape Changes in Myopic Overnight
Orthokeratology. Optometry and Vision Science, 90(3), 196--204.
https://doi.org/10.1097/opx.0b013e31828121eb

					

Yu, L., Li, Z.-K., Gao, J.-R., Liu, J.-R., & Xu, C.-T. (2011). Epidemiology, genetics and
treatments for myopia. International journal of ophthalmology.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3340784/.

				

			

		

	
